name: CI-FRONTEND

on:
  push:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_PROFILE_ENDPOINT: /static/data/user.json
      NEXT_PUBLIC_CATEGORIES_ENDPOINT: /static/data/categoryList.json
      NEXT_PUBLIC_DASHBOARD_ENDPOINT: /static/data/dashboard.json
      NEXT_PUBLIC_CMS_ENDPOINT: https://strapi-lhft.onrender.com/graphql
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install
        run: |
          yarn
      - name: Build
        run: |
          yarn build
      - name: Deploy
        run: |
          aws s3 sync ./out s3://app.tekst.dev
